ABenchM/abm-frontend

- abm-frontend5/abm/src/app/app.component.html
- abm-frontend5/abm/src/app/app.module.ts
- abm-frontend5/abm/src/app/models/search.model.ts
- abm-frontend5/abm/src/app/search/search.component.css
- abm-frontend5/abm/src/app/search/search.component.html
- abm-frontend5/abm/src/app/search/search.component.ts
- abm-frontend5/abm/src/styles.css
create collection component added with stub
> issue #32 fixes

- abm-frontend5/abm/src/app/search/search.component.ts
removed duplicated import, which caused compile errors.
fixed style error (whitespace was used instead of tab)
> fixed duplicated import

- abm-frontend5/abm/src/app/register/register.component.html
- abm-frontend5/abm/src/app/register/register.component.ts
- abm-frontend5/abm/src/app/services/register.service.ts
if username already exists,it won't allow to register with same username. 
Register components are updated with error handling.
> check if username exists fixed

- abm-frontend5/abm/src/app/search/search.component.css
Those errors/warnings that have been reported for the css files, by using csslint, have been fixed.
> Fix errors reported while using csslint

- abm-frontend5/abm/src/app/register/register.component.html
Fix for issue #58 .Prompts the user with a message 'Password is required' if the password is not entered.
> 'Password required' prompted in the Registration form

- abm-frontend5/abm/src/app/services/register.service.ts
- abm-frontend5/abm/src/app/services/utility.service.ts
- abm-frontend5/abm/tslint.json
ts checkstyle fixes (new branch)
> ts checkstyle fixes

- abm-frontend5/abm/package.json
- abm-frontend5/abm/src/app/app.module.ts
- abm-frontend5/abm/src/app/collection/collection.component.ts
- abm-frontend5/abm/src/app/home/home.component.html
- abm-frontend5/abm/src/app/search/search.component.css
- abm-frontend5/abm/src/app/search/search.component.html
resolved merge conflicts for https://github.com/ABenchM/abm-frontend/pull/169.
> fixed merge conflicts and develop branch

- abm-frontend5/abm/src/app/app.module.ts
- abm-frontend5/abm/src/app/bs-navbar/bs-navbar.component.html
- abm-frontend5/abm/src/app/delete-dialogbox/delete-dialogbox.component.html
- abm-frontend5/abm/src/app/delete-dialogbox/delete-dialogbox.component.spec.ts
- abm-frontend5/abm/src/app/delete-dialogbox/delete-dialogbox.component.ts
- abm-frontend5/abm/src/app/manage-users/manage-users.component.css
- abm-frontend5/abm/src/app/manage-users/manage-users.component.html
- abm-frontend5/abm/src/app/manage-users/manage-users.component.spec.ts
- abm-frontend5/abm/src/app/manage-users/manage-users.component.ts
- abm-frontend5/abm/src/index.html
- abm-frontend5/abm/src/styles.css
changes doesnt include the services for backend
> Manage users page for admin

- abm-frontend5/abm/package-lock.json
- abm-frontend5/abm/src/app/app.module.ts
- abm-frontend5/abm/src/app/bs-navbar/bs-navbar.component.css
- abm-frontend5/abm/src/app/bs-navbar/bs-navbar.component.html
- abm-frontend5/abm/src/app/manage-public-collections/manage-public-collections.component.css
- abm-frontend5/abm/src/app/manage-public-collections/manage-public-collections.component.html
- abm-frontend5/abm/src/app/manage-public-collections/manage-public-collections.component.spec.ts
- abm-frontend5/abm/src/app/manage-public-collections/manage-public-collections.component.ts
#134  Change the navigation bar to the proposed UI.
1. Put the logo in the left side.
2. Put the user in the right side.
3. If the user is admin, he sees the Manage public collections, manage users and pending requests.
4. Move My collection from user drop down list to the navigation bar.
5. Add separate tab in navigation bar links to Public collections.
#131 Adding building html and css files to manage public collections.
the used data is faked data
> Navigationbar

- .gitignore
- abm-frontend5/abm/karma.conf.js
- abm-frontend5/abm/src/app/admin-pending-req/admin-pending-req.component.html
- abm-frontend5/abm/src/app/admin-pending-req/admin-pending-req.component.spec.ts
- abm-frontend5/abm/src/app/admin-pending-req/admin-pending-req.component.ts
- abm-frontend5/abm/src/app/app.module.ts
- abm-frontend5/abm/src/app/bs-navbar/bs-navbar.component.spec.ts
- abm-frontend5/abm/src/app/dailog-box/dailog-box.component.html
- abm-frontend5/abm/src/app/dailog-box/dailog-box.component.spec.ts
- abm-frontend5/abm/src/app/dailog-box/dailog-box.component.ts
- abm-frontend5/abm/src/app/dialog-component/dialog-component.component.ts
- abm-frontend5/abm/src/app_theme.scss
#133 Updated headings of tables, added theme for icons, added dailog box for approve request and filter option.
> Admin pendin requests

- abm-frontend5/abm/src/app/admin-pending-req/admin-pending-req.component.html
- abm-frontend5/abm/src/app/admin-pending-req/admin-pending-req.component.ts
- abm-frontend5/abm/src/app/app.module.ts
- abm-frontend5/abm/src/app/dailogbox/dailogbox.component.css
- abm-frontend5/abm/src/app/dailogbox/dailogbox.component.html
- abm-frontend5/abm/src/app/dailogbox/dailogbox.component.spec.ts
- abm-frontend5/abm/src/app/dailogbox/dailogbox.component.ts
#133 updated HTML and CSS files
> Update Admin pending request

- abm-frontend5/abm/src/app/manage-public-collections/manage-public-collections.component.css
- abm-frontend5/abm/src/app/manage-public-collections/manage-public-collections.component.html
- abm-frontend5/abm/src/app/manage-public-collections/manage-public-collections.component.ts
Get real data(public collection) for manage public collections page from the backend.
> get public collection from rest API

- abm-frontend5/abm/src/app/app.module.ts
- abm-frontend5/abm/src/app/manage-public-collections/manage-public-collections.component.html
- abm-frontend5/abm/src/app/manage-public-collections/manage-public-collections.component.ts
- abm-frontend5/abm/src/app/manage-users/manage-users.component.html
- abm-frontend5/abm/src/app/manage-users/manage-users.component.ts
- abm-frontend5/abm/src/app/models/user.model.ts
- abm-frontend5/abm/src/app/register/register.component.ts
- abm-frontend5/abm/src/app/services/collection.service.ts
- abm-frontend5/abm/src/app/services/user.service.spec.ts
- abm-frontend5/abm/src/app/services/user.service.ts
CHanges related to lock/unlock user...services integrated with backend
> Manage users rest api

- abm-frontend5/abm/src/app/delete-dialogbox/delete-dialogbox.component.html
- abm-frontend5/abm/src/app/delete-dialogbox/delete-dialogbox.component.ts
- abm-frontend5/abm/src/app/manage-users/manage-users.component.css
- abm-frontend5/abm/src/app/manage-users/manage-users.component.html
- abm-frontend5/abm/src/app/manage-users/manage-users.component.ts
- abm-frontend5/abm/src/app/services/user.service.ts
SErvices integrated for
- DEleting a user
- Deleting list of users
- LOck/unlock user accounts
- dialog box integration
> Changes for deleting a list of users, lock/unlock user

- abm-frontend5/abm/src/app/admin-pending-req/admin-pending-req.component.html
- abm-frontend5/abm/src/app/admin-pending-req/admin-pending-req.component.ts
- abm-frontend5/abm/src/app/services/user.service.ts
integrated approve and reject buttons with backend #183
> Changes for approving/rejecting a pending user registration request

- abm-frontend5/abm/src/app/admin-pending-req/admin-pending-req.component.ts
- abm-frontend5/abm/src/app/manage-users/manage-users.component.html
- abm-frontend5/abm/src/app/manage-users/manage-users.component.ts
- abm-frontend5/abm/src/app/services/user.service.ts
INtegrated the 'update user role' service.
> Integrated all services for ManageUsers page

- abm-frontend5/abm/src/app/bs-navbar/bs-navbar.component.css
- abm-frontend5/abm/src/app/bs-navbar/bs-navbar.component.html
New merge request for https://github.com/ABenchM/abm-frontend/pull/175
> fix for issue 72

- abm-frontend5/abm/src/app/bs-navbar/bs-navbar.component.css
- abm-frontend5/abm/src/app/bs-navbar/bs-navbar.component.html
Reverts ABenchM/abm-frontend#197
> Revert "fix for issue 72"

- abm-frontend5/abm/src/app/admin-pending-req/admin-pending-req.component.html
- abm-frontend5/abm/src/app/admin-pending-req/admin-pending-req.component.ts
- abm-frontend5/abm/src/app/services/user.service.ts
Multiple select for approve and reject buttons integrated with backend.
> Multipleselect APR

- abm-frontend5/abm/src/app/commit-selector/commit-selector.component.html
- abm-frontend5/abm/src/app/commit-selector/commit-selector.component.ts
> add paginator and search button - issue13&14

- abm-frontend5/abm/src/app/bs-navbar/bs-navbar.component.html
- abm-frontend5/abm/src/app/bs-navbar/bs-navbar.component.ts
- abm-frontend5/abm/src/app/login/login.component.ts
- abm-frontend5/abm/src/app/logout/logout.component.ts
- abm-frontend5/abm/src/app/manage-users/manage-users.component.html
- abm-frontend5/abm/src/app/manage-users/manage-users.component.ts
- abm-frontend5/abm/src/app/services/current-user.service.ts
code changes to check if the logged in user is an Admin or a normal user
> changes for checking the role of a logged in user

- abm-frontend5/abm/src/app/register/register.component.html
- abm-frontend5/abm/src/app/services/register.service.ts
Added lastname in register page #210
> Register component updated

- abm-frontend5/abm/src/app/search/search.component.html
Pull request
about: Updated prompt text on the Create Collection Page.
---
Yes #142 .
> updated prompt text on create collection page

- abm-frontend5/abm/src/app/login/login.component.css
- abm-frontend5/abm/src/app/login/login.component.html
- abm-frontend5/abm/src/app/login/login.component.spec.ts
Pull request
about: Add asterisk(*) to the mandatory fields on the Login page.
Is your pull request related to an issue? Please describe.
Yes. Issue #218
> Feat/fix issue#218

- abm-frontend5/abm/src/app/bs-navbar/bs-navbar.component.css
- abm-frontend5/abm/src/app/bs-navbar/bs-navbar.component.html
---
about: updated different tab color appearing at navigation tab(at username place). 
---
yes. issue #228
> fix for issue#228

- src/app/register/register.component.css
- src/app/register/register.component.html
about: Added asterisks to the registration page.
Is your pull request related to an issue? Please describe.
issue #213
List of functionalities contained in this pull request
Added asterisks to the registration page and fixed previous occurring linting errors.
> fix for issue#213 and fixed previous linting errors

- src/app/login/login.component.html
---
about: Removed not working forgot password link.
---
Yes, issue #254 .
> removed non working Forgot Password Link

- src/app/app.module.ts
- src/app/confirm-password/confirm-password.component.html
- src/app/confirm-password/confirm-password.component.spec.ts
- src/app/confirm-password/confirm-password.component.ts
- src/app/forget-password/forget-password.component.css
- src/app/forget-password/forget-password.component.html
- src/app/forget-password/forget-password.component.spec.ts
- src/app/forget-password/forget-password.component.ts
- src/app/login/login.component.html
- src/app/reset-password-success/reset-password-success.component.html
- src/app/reset-password-success/reset-password-success.component.spec.ts
- src/app/reset-password-success/reset-password-success.component.ts
- src/app/reset-password/reset-password.component.html
- src/app/reset-password/reset-password.component.spec.ts
- src/app/reset-password/reset-password.component.ts
- src/app/services/reset-password.service.spec.ts
- src/app/services/reset-password.service.ts
about: Users can reset their password when forgotten.
Is your pull request related to an issue? Please describe.
Yes. #164 , #199 .
List of functionalities contained in this pull request
Forgot and Reset password feature ( from home page )
sends reset email
and on click on link opens reset password page and updates password.
> Functionality for resetting password for a user

- src/app/about/about.component.css
- src/app/about/about.component.html
- src/app/about/about.component.spec.ts
- src/app/app.module.ts
- src/app/login/login.component.spec.ts
---
about: Suggest a change in the code of this project
---
A clear and concise description of what the issue is. Please reference an existing issue when possible.
**List of functionalities contained in this pull request**
A clear and concise description of each one of the functionalities.
**List of the test cases**
A clear and concise description of the test cases contained in this pull request, and which functionalities they cover.
> Refactored AboutComponent html template 

- src/app/services/user.service.ts
---
about: If the current user is an Admin then it should not appear in the Manage Users tab.
---
Yes, #285 .
Passing all test cases and linting errors.
> curresnt user Admin should not appear in mamage users tab

- src/app/search/search.component.html
- src/app/search/search.component.ts
---
name: Implemented show search result on table
about: Display search result 
---
This is a continuation of issue #248.
**List of functionalities contained in this pull request**
A Search function that queries the Delphi search endpoint and returns value that match the search query.
A table that binds to the data returned by the search function
> Show search result on table

- src/app/home/home.component.css
- src/app/home/home.component.html
- src/app/home/home.component.ts
name: Updated table of public collection page
about: Added version column for public and pinned collection
**List of functionalities contained in this pull request**
Added Version column which contains show version button for each collection. Once you click this button it gets expand and provides the versions of particular version.
All the cases are passed, please find below screenshot for the same.
> Added version column to public collection and pinned collection table

- src/app/app.module.ts
---
about: Fixed error in develop branch.
---
Yes #301 
Passing of all test cases (below):
> fix in develop for error in issue #301

- src/app/register/register.component.html
- src/app/register/register.component.ts
- src/app/services/register.service.ts
---
about: One used email id cannot be used again for registering to the application.
---
Yes, #309 .
To test this functionality please use the back-end PR: https://github.com/ABenchM/abm/pull/337
Passing all test cases:
> existing email can not be reused for creating a new account

- src/app/edit-collection/edit-collection.component.css
- src/app/edit-collection/edit-collection.component.html
- src/app/edit-collection/edit-collection.component.spec.ts
- src/app/edit-collection/edit-collection.component.ts
---
about: To ensure styling consistency - changed the existing structure of edit collection component from Bootstrap to Angular Material.
---
Yes #312 
Passing of test cases and linting files:
> updated edit collection page with use of angular material

- npm-shrinkwrap.json
- src/app/home/home.component.html
- src/app/home/home.component.ts
---
about: Fix for the bug "paginator not working" on the Public Collection's page.
---
Yes, #334 
Passing of test cases
> fixed paginator issue on public collections page

- package.json
- src/app/app.module.ts
- src/app/bs-navbar/bs-navbar.component.html
- src/app/home/home.component.html
- src/app/home/home.component.ts
- src/app/on-boarding/on-boarding.component.css
- src/app/on-boarding/on-boarding.component.html
- src/app/on-boarding/on-boarding.component.spec.ts
- src/app/on-boarding/on-boarding.component.ts
---
name: OnBoarding tutorial
about: related to iss #343 
---
> Implemented animated tutorial for user onboarding
